export enum TokenContract_Methods {
  TransferFungible = 0,
  TransferNonFungible = 1,
  CreateToken = 2,
  MintFungible = 3,
  BurnFungible = 4,
  GetBalance = 5,
  CreateTokenSeries = 6,
  DeleteTokenSeries = 7,
  MintNonFungible = 8,
  BurnNonFungible = 9,
  GetInstances = 10,
  GetNonFungibleInfo = 11,
  GetNonFungibleInfoByRomId = 12,
  GetSeriesInfo = 13,
  GetSeriesInfoByMetaId = 14,
  GetTokenInfo = 15,
  GetTokenInfoBySymbol = 16,
  GetTokenSupply = 17,
  GetSeriesSupply = 18,
  GetTokenIdBySymbol = 19,
  GetBalances = 20,
  CreateMintedTokenSeries = 21,
}
