import { VmDynamicStruct, VmNamedDynamicVariable, VmNamedVariableSchema, VmType } from "../../Vm";
import { StandardMeta } from "../StandardMeta";

export class MetadataField {
  name: string;
  value: string | number | Uint8Array;
}

export class FieldType {
  name: string;
  type: VmType;
}

export const seriesDefaultMetadataFields: readonly FieldType[] = [
  { name: StandardMeta.id.data, type: VmType.Int256 }, // Mandatory field, autogenerated by SDK
  { name: 'mode', type: VmType.Int8 },
  { name: 'rom', type: VmType.Bytes }
] as const;

export const nftDefaultMetadataFields: readonly FieldType[] = [
  { name: StandardMeta.id.data, type: VmType.Int256 }, // Mandatory field, autogenerated by SDK
  { name: 'rom', type: VmType.Bytes }
] as const;

export const standardMetadataFields: readonly FieldType[] = [
  { name: 'name', type: VmType.String },
  { name: 'description', type: VmType.String },
  { name: 'imageURL', type: VmType.String },
  { name: 'infoURL', type: VmType.String },
  { name: 'royalties', type: VmType.Int32 }
] as const;

export function findMetadataField(fields: MetadataField[], name: string): MetadataField {
  return fields.find(f => f.name.toLowerCase() === name.toLowerCase());
}

export function pushMetadataField(fieldSchema: VmNamedVariableSchema, metadata: VmDynamicStruct, metadataFields: MetadataField[]): void {
  let found = metadataFields.find(f => f.name === fieldSchema.name.data);
  if (!found) {
    found = metadataFields.find(f => f.name.toLowerCase() === fieldSchema.name.data.toLowerCase());
    if (found) {
      throw Error(`Metadata field '${fieldSchema.name.data}' provided in incorrect case: '${found.name}'`);
    }
    throw Error(`Metadata field '${fieldSchema.name.data}' is mandatory`);
  }
  
  if (fieldSchema.schema.type === VmType.String && typeof found.value === "string") {
    if (found.value && found.value.trim().length != 0) {
      metadata.fields.push(VmNamedDynamicVariable.from(fieldSchema.name, fieldSchema.schema.type, found.value));
    } else {
      throw Error(`Metadata field '${fieldSchema.name.data}' is mandatory`);
    }
  } else {
    metadata.fields.push(VmNamedDynamicVariable.from(fieldSchema.name, fieldSchema.schema.type, found.value));
  }
}

